
app = "peer2peer"
primary_region = "iad"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "peer2peer.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "peer2peer_data"
  destination = "/data"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "/app/bin/migrate"
